[package]
name = "backend"
version = "0.1.0"
authors = ["Tarek Ali <tarekali15@outlook.com>"]
edition = "2018"
ws = "0.9.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
